Feature/add jwt and login module
calandnong/ling-wu-web-server pull request #10
Opened 2023-05-11 08:11 UTC by zhutongtian

增加登录、注册、jwt模块以及对应的功能实现

2023-05-11 09:24 UTC, calandnong requested changes
这些内容需要重新关注下

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.service.ts
> +      throw new ForbiddenException('用户不存在，请注册');
错误考虑收敛一下，给前端一个统一的业务码？而非http错误码

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.service.ts
> +      throw new ForbiddenException('用户名或者密码错误');
错误考虑收敛一下，给前端一个统一的业务码？而非http错误码

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.service.ts
> +      throw new ForbiddenException('用户已存在');
错误考虑收敛一下，给前端一个统一的业务码？而非http错误码，后面的错误抛出同上

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.strategy.ts
> +export class JwtStrategy extends PassportStrategy(Strategy) {
PassportStrategy(Strategy) 改为 PassportStrategy(Strategy, 'jwt')

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.strategy.ts
> +  async validate(payload: any) {
payload标注下类型

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/auth/jwt.constants.ts
> +export const jwtConstants = {
考虑下配置化？

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/auth/local.strategy.ts
> +export class LocalStrategy extends PassportStrategy(Strategy) {
PassportStrategy(Strategy) 改为 PassportStrategy(Strategy, 'local')

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/auth/local.strategy.ts
> +  async validate(username: string, password: string): Promise<any> {
any 改为 User

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/user/pipes/create-user.pipe.ts
> +export class CreateUserPipe implements PipeTransform {
加一下功能注释，本次版本的代码以及功能都加一下相关的注释，不用很详细，但是需要注释，如果涉及到配置的，更新一下相关的文档描述

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/user/user.controller.ts
> +  @Post()
加上swagger的参数描述，因为这边后面接口统一走swagger的作为文档

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/user/user.service.ts
> +  find(username: string) {
加一下多行注释对当前函数的

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/user/user.service.ts
> +    return this.userRepository.findOne({ where: { username } });
可以关注下这个的类型为什么不返回null？

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/user/user.service.ts
> +    const userTmp = await this.userRepository.create(user);
注释，函数注释以及逻辑注释

2023-05-11 09:24 UTC, calandnong commented on packages/pc-server/src/modules/user/dto/create-user.dto.ts
> +export class CreateUserDto {
注释

2023-05-11 11:18 UTC, calandnong requested changes
完成第二次review

2023-05-11 11:18 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.controller.ts
> +    return this.authService.signin(username, password);
<img width="702" alt="image" src="https://github.com/calandnong/ling-wu-web-server/assets/50078867/c5297b80-8458-42ea-80ba-1bb16a2e6ebf">
你的signin可以考虑小驼峰的命名？signin这里有多余的参数【password】建议删除，考虑dto中是否也需要

2023-05-11 11:18 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.controller.ts
> +    return this.authService.signin(username, password);
小驼峰方式写函数和方法，比如：
<img width="576" alt="image" src="https://github.com/calandnong/ling-wu-web-server/assets/50078867/691125cb-ae36-4e7f-8ce8-196c926a0a0a">

2023-05-12 06:59 UTC, zhutongtian commented on .vscode/settings.json
> +  "editor.formatOnSave": true,
已安装eslint

2023-05-12 07:01 UTC, zhutongtian commented on README.md
> +windows: pnpm --filter @ling-wu-server/pc-server run start
觉得"pnpm --filter @ling-wu-server/pc-server run start"比较麻烦，改动之后还得重启，修改成"pnpm --filter @ling-wu-server/pc-server run start:dev"了

2023-05-12 07:01 UTC, zhutongtian commented on packages/pc-server/config/config.development.yaml
> +  username: 'root'
已恢复，之前不明白config.development.yaml和config.development.local.yaml的意义

2023-05-12 07:02 UTC, zhutongtian commented on packages/pc-server/config/config.development.yaml
> +  password: '123456'
已恢复

2023-05-12 07:02 UTC, zhutongtian commented on packages/pc-server/src/main.ts
> +  app.useGlobalPipes(
已处理

2023-05-12 07:02 UTC, zhutongtian commented on packages/pc-server/src/modules/user/user.controller.ts
> +  @Post()
已加

2023-05-12 07:02 UTC, zhutongtian commented on packages/pc-server/src/modules/user/user.service.ts
> +  find(username: string) {
已加

2023-05-12 07:02 UTC, zhutongtian commented on packages/pc-server/src/modules/user/user.service.ts
> +    const userTmp = await this.userRepository.create(user);
已加

2023-05-12 07:03 UTC, zhutongtian commented on packages/pc-server/src/modules/user/dto/create-user.dto.ts
> +export class CreateUserDto {
已加

2023-05-12 07:16 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.controller.ts
> +    return this.authService.signin(username, password);
> <img alt="image" width="702" src="https://user-images.githubusercontent.com/50078867/237669174-c5297b80-8458-42ea-80ba-1bb16a2e6ebf.png"> 你的signin可以考虑小驼峰的命名？signin这里有多余的参数【password】建议删除，考虑dto中是否也需要

password有用，入库加密

2023-05-12 07:16 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.controller.ts
> +    return this.authService.signin(username, password);
驼峰已改

2023-05-12 07:17 UTC, zhutongtian commented on packages/pc-server/src/main.ts
> +    new ValidationPipe({
已改

2023-05-12 07:17 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.controller.ts
> +  @Post('/signin')
已加

2023-05-12 07:22 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.service.ts
> +    if (user && user.password === pass) {
已改

2023-05-12 07:29 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.service.ts
> +      throw new ForbiddenException('用户不存在，请注册');
已使用BaseResponse.toErrorJustMessage()

2023-05-12 07:29 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.service.ts
> +      throw new ForbiddenException('用户名或者密码错误');
已使用BaseResponse.toErrorJustMessage()

2023-05-12 07:29 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.service.ts
> +      throw new ForbiddenException('用户已存在');
已使用BaseResponse.toErrorJustMessage()

2023-05-12 07:30 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.service.ts
> +  async validateUser(username: string, pass: string): Promise<any> {
已改

2023-05-12 07:33 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.strategy.ts
> +export class JwtStrategy extends PassportStrategy(Strategy) {
![Uploading image.png…]()

2023-05-12 07:55 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.strategy.ts
> +  async validate(payload: any) {
已改

2023-05-12 07:55 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/jwt.constants.ts
> +export const jwtConstants = {
已放

2023-05-12 07:57 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/local.strategy.ts
> +export class LocalStrategy extends PassportStrategy(Strategy) {
已加

2023-05-12 08:14 UTC, zhutongtian commented on packages/pc-server/src/modules/user/pipes/create-user.pipe.ts
> +export class CreateUserPipe implements PipeTransform {
已加

2023-05-12 08:15 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/local.strategy.ts
> +  async validate(username: string, password: string): Promise<any> {
已删除local.strategy.ts文件

2023-05-12 09:11 UTC, calandnong requested changes
新review的点

2023-05-12 09:11 UTC, calandnong commented on packages/pc-server/src/modules/user/user.controller.ts
> +  @Post()
dto的注释没有？

2023-05-12 09:11 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.controller.ts
> +  signUp(@Body() dto: SignUserDto) {
dto加下swagger注释

2023-05-12 09:11 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.service.ts
> +  constructor(private userService: UserService, private jwt: JwtService) {}
命名为xxxService，这里是不是可以：jwtService

2023-05-12 09:11 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.controller.ts
> +  signIn(@Body() dto: SignUserDto) {
dto如下

2023-05-13 14:41 UTC, calandnong requested changes
验证登陆逻辑

2023-05-13 14:41 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.service.ts
> +      password,
密码不加密入库？

2023-05-13 14:41 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.service.ts
> +      password,
上面的报错可以考虑下通用的错误抛出

2023-05-13 14:43 UTC, calandnong commented on packages/pc-server/src/modules/auth/auth.service.ts
> +    return await this.jwt.signAsync({
这个地方不需要await

2023-05-15 00:28 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.service.ts
> +    return await this.jwt.signAsync({
已改

2023-05-15 00:32 UTC, zhutongtian commented on packages/pc-server/src/modules/auth/auth.controller.ts
> +  signIn(@Body() dto: SignUserDto) {
已加

2023-05-15 03:14 UTC, zhutongtian commented on packages/pc-server/src/modules/user/user.service.ts
> +    return this.userRepository.findOne({ where: { username } });
![image](https://github.com/calandnong/ling-wu-web-server/assets/33335983/c59a6fec-7b95-44de-be7f-92c1af1cc371)

2023-05-15 06:36 UTC, calandnong approved these changes

2023-05-15 10:51 UTC, calandnong approved these changes
LGTM

2023-05-15 10:52 UTC, merged